apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-availability.my-apps.tap.20240526081125.0.0+build.6aff574
spec:
  refName: where-for-dinner-availability.my-apps.tap
  version: 20240526081125.0.0+build.6aff574
  releaseNotes: |
    Release v20240526081125.0.0+build.6aff574 of package where-for-dinner-availability.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/tap-ci/ci-pipeline/apps-25-05-2024-22-57-25-803768973/where-for-dinner-availability-my-apps-bundle@sha256:f549f19e160ad50926970ad282f10ae050afa5acf381433f6ba41d135a13c262
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""
          minLength: 1

